⚡️ 🚧 move to ramdisk for optimising

diff --git a/templates/autocal.tmpl b/templates/autocal.tmpl
--- a/templates/autocal.tmpl
+++ b/templates/autocal.tmpl
@@ -30,6 +30,17 @@ fi
 echo "jobid: ${jobid}"
 echo "taskid: ${taskid}"
 
+if [[ -n $TMPDIR_SHM && -d $TMPDIR_SHM ]];then
+    ramDiskBase=$TMPDIR_SHM
+else
+    ramDiskBase=$(mktemp -d /dev/shm/${jobid}_${taskid}.XXX)
+fi
+tempdir="${ramDiskBase}/${jobid}_${taskid}"
+mkdir -p "$tempdir"
+[[ -d $tempdir ]] || die "RAM disk creation unsuccessful: $tempdir"
+trap "rm -rf $ramDisk" EXIT
+# tempdir=${GXTEMP}/${jobid}_${taskid}/
+
 function test_fail {
 if [[ $1 != 0 ]]
 then
@@ -77,6 +88,8 @@ ts=10
 singularity run ${GXCONTAINER} track_task.py start --jobid="${jobid}" --taskid="${taskid}" --start_time="$(date +%s)"
 
 cd "${datadir}/${obsnum}" || exit
+
+
 
 metafits="${obsnum}.metafits"
 if [[ ! -e ${metafits} ]] || [[ ! -s ${metafits} ]]
@@ -127,10 +140,12 @@ calmodel="${obsnum}_local_gleam_model.txt"
 
 
 cd "${datadir}/${obsnum}" || exit
-
+cp -rf ${obsnum}.ms ${tempdir}/
 # Check whether the phase centre has already changed
 # Calibration will fail if it has, so measurement set must be shifted back to its original position
-current=$(singularity run $GXCONTAINER chgcentre "${obsnum}.ms") 
+current=$(singularity run $GXCONTAINER chgcentre "${tempdir}/${obsnum}.ms") 
+
+
 
 if [[ $current == *"shift"* ]] 
 then
@@ -138,7 +153,7 @@ then
     coords=$(singularity run $GXCONTAINER calc_optimum_pointing.py --metafits "${metafits}")
     echo "Optimally shifting co-ordinates of measurement set to $coords, without zenith shiftback."
     singularity run ${GXCONTAINER} chgcentre \
-            "${obsnum}.ms" \
+            "${tempdir}/${obsnum}.ms" \
             ${coords}
 else
     echo "Detected that this measurement set has not yet had its phase centre changed. Not shifting."
@@ -155,15 +170,16 @@ maxuvm=$(echo "390000 / (${chan} + 11)" | bc -l)
 
 if [[ ! -z $ion ]]
 then
-    echo "Performing ionospheric triage using calibrate. "
-    # Ionospheric triage
-    solutions="${obsnum}_${calmodel%%.txt}_solutions_ts${ts}.bin"
-    # Remove duplicate obsnum
-    solutions="${solutions/${obsnum}_${obsnum}_/${obsnum}_}"
-
     
     if [[ ! -z ${ao_calibrate} ]]
     then 
+
+        echo "Performing ionospheric triage using calibrate. "
+        # Ionospheric triage
+        solutions="${obsnum}_${calmodel%%.txt}_solutions_ts${ts}.bin"
+        # Remove duplicate obsnum
+        solutions="${solutions/${obsnum}_${obsnum}_/${obsnum}_}"
+
         singularity run $GXCONTAINER calibrate \
                 -t ${ts} \
                 -j ${SLURM_CPUS_PER_TASK} \
@@ -172,7 +188,7 @@ then
                 -minuv ${minuvm} \
                 -maxuv ${maxuvm} \
                 -applybeam -mwa-path "${MWAPATH}" \
-                "${obsnum}.ms" \
+                "${tempdir}/${obsnum}.ms" \
                 "${solutions}"
         
         echo "Ionospheric calibration finished. Creating plots and statistics. "
@@ -195,7 +211,7 @@ then
             --uvw-max 1667lambda \
             --beam-file "${MWAPATH}/mwa_full_embedded_element_pattern.h5" \
             --outputs "${solutions1}" \
-            -d "${obsnum}.ms" "${obsnum}.metafits" \
+            -d "${tempdir}/${obsnum}.ms" "${obsnum}.metafits" \
             -s ${calmodel}
         
         singularity run $GXCONTAINER hyperdrive \
@@ -242,7 +258,7 @@ then
             --uvw-max 1667lambda \
             --beam-file "${MWAPATH}/mwa_full_embedded_element_pattern.h5" \
             --outputs "${solutions}" \
-            -d "${obsnum}.ms" "${obsnum}.metafits" \
+            -d "${tempdir}/${obsnum}.ms" "${obsnum}.metafits" \
             -s ${calmodel}
         
         
@@ -276,7 +292,7 @@ then
             -minuv $minuvm \
             -maxuv $maxuvm \
             -applybeam -mwa-path "${MWAPATH}" \
-            "${obsnum}".ms \
+            "${tempdir}/${obsnum}".ms \
             "${solutions}"
 else
     singularity run $GXCONTAINER hyperdrive \
@@ -287,7 +303,7 @@ else
         --uvw-max 1667lambda \
         --beam-file "${MWAPATH}/mwa_full_embedded_element_pattern.h5" \
         --outputs "${solutions}" \
-        -d "${obsnum}.ms" "${obsnum}.metafits" \
+        -d "${tempdir}/${obsnum}.ms" "${obsnum}.metafits" \
         -s ${calmodel}
 fi 
 
@@ -295,7 +311,7 @@ test_fail $?
 
 # Create a version divided through by the reference antenna, so that all observations have the same relative XY phase, allowing polarisation calibration solutions to be transferred
 # This also sets the cross-terms to zero by default
-singularity run ${GXCONTAINER} aocal_phaseref.py "${solutions}" "${solutions%.bin}_ref.bin" "${refant}" --xy -2.806338586067941065e+01 --dxy -4.426533296449057023e-07  --ms "${obsnum}.ms"
+singularity run ${GXCONTAINER} aocal_phaseref.py "${solutions}" "${solutions%.bin}_ref.bin" "${refant}" --xy -2.806338586067941065e+01 --dxy -4.426533296449057023e-07  --ms "${tempdir}/${obsnum}.ms"
 
 if [[ ! -z ${ao_calibrate} ]]
 then 
@@ -318,7 +334,21 @@ result=$(singularity run $GXCONTAINER check_assign_solutions.py -t "${fraction}"
 if echo "${result}" | grep -q fail
 then
     mv "${solutions%.bin}_ref.bin" "${solutions%.bin}_ref_failed.bin"
-    test_fail 1
+    # test_fail 1
 fi
+
+rm -rf ${tempdir}/
+
+# if [[ -e "${solutions%.bin}_ref.bin" ]] || [[ -e "${solutions%.bin}_ref_failed.bin" ]]
+# then
+#     echo "There are calibration solutions (may or may not have failed)" 
+#     # rm -rf ${obsnum}.ms && cp -rf ${tempdir}/${obsnum}.ms ./
+#     rm -rf ${tempdir}/
+# else 
+#     echo "There is no final image so I haven't subtracted anything because I'm not sure what's wrong" 
+#     rm -rf ${tempdir}/${obsnum}.ms
+#     # exit 1
+    
+# fi 
 
 singularity run ${GXCONTAINER} track_task.py finish --jobid="${jobid}" --taskid="${taskid}" --finish_time="$(date +%s)"
